/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jp.kusumotolab.prepareExp;

import org.junit.Test;

import java.io.IOException;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;

public class AppTest {
    @Test
    public void test() throws IOException {
        final Path sample = Paths.get("sample");
        final List<Path> paths = App.getAllJavaPath(sample);
        assertThat(paths).hasSize(3);
    }

    @Test
    public void testApply() throws IOException {
        final String[] args = {"sample/apply", "0"};
        App.main(args);
    }
}
